### ISSUE TITLE
align get latex button and add status

### ISSUE THREAD

**Issue by 0x0is1** [MostlyKIGuess/handwritten-to-LaTeX-demo#10]
### Frontend

- [x] Align get latex button somewhere in the middle. maybe in between both container (draw and preview)
- [x] Add 4 status box on top to provide information about model like model_name/version, model_accuracy, loss_rate, last updated (make it look good, in diff colors)

**Comment by MostlyKIGuess** [comment]
#11 adios

**Comment by 0x0is1** [comment]
@MostlyKIGuess I created this issue. You don't get to close it without a review from me. Take care from next time. Good Job!
